### ISSUE TITLE
Could not find gem 'itamae-plugin-resource-iptables (>= 0) ruby'

### ISSUE THREAD

**Issue by namusyaka** [namusyaka/itamae-plugin-resource-iptables#1]
Could you push this gem into rubygems.org?

**Comment by eagletmt** [comment]
Actually I'm not using this gem now!
If you're using this gem, I'll transfer this repository to you and feel free to push it to rubygems.org .
Are you interested in it?

**Comment by namusyaka** [comment]
Thank you for your kindness!
Yes, I'm interested in that.
I'd like to use this cool gem!

**Comment by eagletmt** [comment]
I just requested repository transfer to you.

**Comment by namusyaka** [comment]
Thank you so much! :heart:

**Comment by namusyaka** [comment]
Closed via https://rubygems.org/gems/itamae-plugin-resource-iptables
